# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('capacity', models.IntegerField(default=100)),
                ('pincode', models.IntegerField(default=751020)),
            ],
        ),
        migrations.CreateModel(
            name='market_crop_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.IntegerField(default=100)),
                ('crop_price_prev_kharif', models.IntegerField(default=100, help_text=b'1 year ago per kg Kharif')),
                ('crop_price_prev_rabi', models.IntegerField(default=100, help_text=b'1 year ago per kg rabi')),
                ('crop_price_prev1_kharif', models.IntegerField(default=100, help_text=b'2 year ago per kg Kharif')),
                ('crop_price_prev2_rabi', models.IntegerField(default=100, help_text=b'2 year ago per kg rabi')),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_warehouse.Crop')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Market')),
            ],
        ),
    ]
