# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=30)),
                ('catagory', models.CharField(help_text='Kharif or Rabi', max_length=30)),
                ('crop_price_cur', models.IntegerField()),
                ('crop_price_prev_kharif', models.IntegerField(default=100, help_text='1 year ago per kg Kharif')),
                ('crop_price_prev_rabi', models.IntegerField(default=100, help_text='1 year ago per kg rabi')),
                ('crop_price_prev1_kharif1', models.IntegerField(default=100, help_text='2 year ago per kg Kharif')),
                ('crop_price_prev2_rabi1', models.IntegerField(default=100, help_text='2 year ago per kg rabi')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('capacity', models.IntegerField(default=100)),
                ('price', models.IntegerField(default=100, help_text='monthly price')),
                ('pincode', models.IntegerField(default=751020)),
            ],
        ),
    ]
