# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_company_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('capacity_per_person', models.IntegerField(default=100, help_text='per person capacity')),
                ('trip_price_per_km', models.IntegerField(default=100, help_text='per km')),
                ('pincode', models.IntegerField(default=751020)),
            ],
        ),
    ]
